### ISSUE TITLE
Save bandwidth with CloudFlare CDN

### ISSUE THREAD

**Issue by laukstein** [DMarby/unsplash-it#16]
I see Unsplash It having big bandwidth. You can save lots of bandwidth by simply applying CloudFlare DNS that would pass all network trough their proxy - secure, cached and optimized.

In CloudFlare you can define 'Page Rule' to "Cache everything", add addition role `https://unsplash.it/*?random` "Bypass cache".

**Comment by DMarby** [comment]
Bandwidth isn't really an issue, the only compelling reason to use a CDN would be for a slight speedup.

**Comment by laukstein** [comment]
CloudFlare isn't CDN service, but the way they delivers any content (also dynamic content from free plan) is trough their CDN earlier caching all requests from origin server.
