### ISSUE TITLE
Search endpoint for the API

### ISSUE THREAD

**Issue by redaxmedia** [DMarby/unsplash-it#19]
Hello,

I'd like to suggest a API endpoint to search for images. There are great auto tagging services to create a cached dataset for each image. A cronjob would be great to automate the whole process.

<pre>
https://unsplash.it/200/300/?search=keyword
</pre>

Check out the code examples: http://imagga.com/auto-tagging-demo

Let me know if I can give you a helpful hand...

**Comment by andela-rekemezie** [comment]
Really makes sense. @redaxmedia are there currently endpoints to search images on the platform?

**Comment by redaxmedia** [comment]
@andela-rekemezie Nope, not yet.

**Comment by andela-rekemezie** [comment]
@redaxmedia What about this: `https://api.unsplash.com/photos/search/?client_id=${application_id}&query=${search_param}&page=1`

**Comment by redaxmedia** [comment]
Looks promising, thank you! I gonna close that issue and switch to unsplash.com...
