### ISSUE TITLE
How to get image extension?

### ISSUE THREAD

**Issue by Gabriellavoura** [DMarby/unsplash-it#24]
I want to get a link to a random image with the extension (such as .png or .jpeg) to test an app with ionic2 / angular 2, how do I do this?
I know the link obtained by the site contains an id as http://unsplash.it/400/img=ID.
Idont want download the image, just view it.

I need something like:

http://unsplash.it/400/random_Img_url.png
or
http://unsplash.it/400/random_img_url.jpg

Thanks.

**Comment by DMarby** [comment]
Hello,

you can either do 
https://unsplash.it/400/400.png
or https://unsplash.it/400/400.png?image=<ID>

**Comment by Gabriellavoura** [comment]
Yes, this solved my problem! thx o/
