### ISSUE TITLE
Can I combine the ?blur and ?image=138 to get a specific blurred image? 

### ISSUE THREAD

**Issue by santiagopliego** [DMarby/unsplash-it#29]

**Comment by birjolaxew** [comment]
The options are simple GET parameters. `?` indicates the start of the parameters, and `&` separates parameters if there are multiple. To combine them, you'd just do `https://unsplash.it/512/256?image=1&blur`.

**Comment by santiagopliego** [comment]
@birjolaxew Thank you! Makes perfect sense.

**Comment by nijikokun** [comment]
Seems this was answered :tada: Closing!
