### ISSUE TITLE
Is there a reason that some id's are not valid?

### ISSUE THREAD

**Issue by parterburn** [DMarby/unsplash-it#30]
For example, ID 97 doesn't exist. I'm using this service to grab a random image, but associating it to the first byte character so it only changes on the object if the slug changes. But pretty randomly, certain characters will make it fail.

**Comment by DMarby** [comment]
Hi,

The id's that doesn't exist anymore are of photos that had been deleted from unsplash.com. Any time that occurs, that id will stop working.
