### ISSUE TITLE
Unsplash-cli

### ISSUE THREAD

**Issue by ladislas** [DMarby/unsplash-it#4]
Hi there!

This is not an issue, just a little message to thank you for your amazing work and for making it open source :)

I've been playing recently with node.js and wanted to learn how to build a cli application so I decided to make a cli version of unsplash-it, unsurprisingly called unsplah-cli.

Not sure if it is really useful to anyone, but here it is: https://www.npmjs.com/package/unsplash-cli

If you're on OS X you can use `unsplash desktop --random` to get a random desktop background image! yeah! ;)

**Comment by cliffordp** [comment]
:+1:

**Comment by DMarby** [comment]
Hey,

awesome to see cool stuff being made using unsplash.it :) 
Will definitely give it a try!
