### ISSUE TITLE
Attempting to use /list/ gives a 'Resource not found' error

### ISSUE THREAD

**Issue by bigbeno37** [DMarby/unsplash-it#5]
Just messing around with the API via Google Chrome, and after using https://unsplash.it/1920/1080/?random a bunch, I decided to try and get a list of all unsplash images that are those dimensions. However, using either https://unsplash.it/list/1920/1080/ or https://unsplash.it/1920/1080/list/ results in Chrome displaying this error message:

{"error":"Resource not found"}

Maybe I'm doing something wrong, but it'd be nice to be able to see a list of all possible images of these dimensions.

**Comment by DMarby** [comment]
Hello, 

there's no endpoint for doing that, as the info from the https://unsplash.it/list endpoint should be more than enough. Simply check the "width" and "height" property for each image, and keep in mind that all images can be resized to a smaller size than their width/height.

Sincerely,
David

**Comment by bigbeno37** [comment]
Alright, what if I wanted to have a list of all unsplash images that have a specific width and height?

**Comment by cliffordp** [comment]
I like the idea too. For example, if looking for 4x3 or 16x9 or something ≥ 1920

**Comment by DMarby** [comment]
I'm not sure if I'm misunderstanding you, or if you are misunderstanding how Unsplash It works.
The easiest way for you to get your result would be to check the sizes of every image in the list, and build your own list based on that.

**Comment by bigbeno37** [comment]
However, would it be possible for that check to occur on your end instead of ours?

**Comment by DMarby** [comment]
No.
