### ISSUE TITLE
Multiple random images with same size, end up as the same image...

### ISSUE THREAD

**Issue by iammarkoradak** [DMarby/unsplash-it#6]
Hey David,

Just wanted to drop you a note on this... While it’s really great to pull a random gorgeous image whenever you need one, it would be that much better if when pulling multiple random images with the same size - pulled images actually come random. The way it currently is you end up with n instances of the same image.

Any way you could look it up? I think many would benefit from it :)

Cheers

**Comment by DMarby** [comment]
Hi, this is due to how most  browsers handles resource requests. You can add ?random=<something_random_here> that's different for every image to achieve the result you want.

**Comment by unetics** [comment]
Awesome Really think you should add this info to your website
