### ISSUE TITLE
A way to use "background-size: cover;"?

### ISSUE THREAD

**Issue by Magnus-G** [DMarby/unsplash-it#9]
Thanks for a great tool!

My question is if there is a way to avoid having to specify the size of the image in the markup? Instead I'd like to do that in the CSS by telling the image to cover its container if possible. 

I run into this issue when I use media queries that allow multiple columns of images collapse into one single column (thus having the image spread across the screen).

**Comment by DMarby** [comment]
Hello, you can do /0/0 to get the largest available resolution of an image (does not scale up above the default dimensions). However, I would recommend just using a large enough resolution that should fit most screens, or similar.

**Comment by Magnus-G** [comment]
Thank you for your quick response! 0/0 works great. 
Another (maybe off topic) question: is there a way to create more than one randomized selection for one page load? If I do the following I get two identical images, but I'd prefer two randomized (thus different):

```
<img src="https://unsplash.it/0/0?random" alt="">
<img src="https://unsplash.it/0/0?random" alt="">
```

**Comment by DMarby** [comment]
You can do ?random=1, ?random=2 or add any other random parameter to avoid the browser caching the image and ending up with the same one

**Comment by Magnus-G** [comment]
Wonderful! Thank you.
